[package]

name = "baby_linguist"
version = "0.0.1"
authors = [ "Acshi Haggenmiller <acshikh@gmail.com>", "Jake Brawer <jake.brawer@yale.edu>" ]

[dependencies]
image = "*"
time = "*"
rustfft = "*"
num = "*"
<<<<<<< HEAD
=======
glob = "*"
conrod = { version = "*", features = ["glium", "winit"] }
>>>>>>> 5028f8c856b1d234d76bb3f37cf86bc641aee624

